package de.telekobold.ideacloud.codegenerator;

import java.io.IOException;

import de.telekobold.ideacloud.IdeaCloudTriple;

/**
 * 
 * Parts of the generated cloud tag HTML code skeleton are derived from the
 * <a href=
 * "https://dev.to/alvaromontoro/create-a-tag-cloud-with-html-and-css-1e90">cloud
 * tag generation tutorial</a> from Alvaro Montoro.
 * 
 * @author telekobold
 */
public class IdeaCloudHtmlGenerator extends IdeaCloudAbstractGenerator {

    private final HtmlBuilder ideaCloud_html;

    public IdeaCloudHtmlGenerator(String filename) {
	super(filename);
	ideaCloud_html = new HtmlBuilder();
    }

    /**
     * Generates HTML code from the content of {@code inputTags} and stores it in
     * this object's {@code HtmlBuilder} attribute.
     * 
     * @param inputTags array storing the content to be written into the HTML file
     *                  to be generated
     */
    public void generateIdeaCloudHtmlContent(IdeaCloudTriple<String, Integer, String>... inputTags) {
	// System.out.print("Start HTML file generation... ");

	ideaCloud_html.comment("This file was generated by IdeaCloudHtmlGenerator.java")
		.nl()
		.add("<!DOCTYPE html>")
		.add("<html>")
		.add("<head>")
		.add("<meta charset=\"utf-8\">")
		.add("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
		.add("<link rel=\"stylesheet\" type=\"text/css\" href=\"")
		// Reuse the .html file name of this file and replace the ".html" by a ".css":
		.append(filename.substring(0, filename.length() - 5))
		.append(".css\">")
		.add("</head>")
		.add("<body>")
		.add("<header>")
		.add("<h1>IdeaCloud</h1>")
		.add("</header>")
		.add("<main>")
		.add("<ul class=\"cloud\" role=\"navigation\" aria-label=\"idea tag cloud for planning\">");

	for (IdeaCloudTriple<String, Integer, String> inputTag : inputTags) {
	    ideaCloud_html.add("<li><a href=\"./data/")
		    .append(inputTag.getTagName() + ".html")
		    .append("\" data-weight=\"")
		    .append(Integer.toString(inputTag.getWeight()))
		    .append("\"");
	    if (inputTag.getDeadline() != null) {
		ideaCloud_html.append(" deadline=\"")
			.append(inputTag.getDeadline())
			.append("\"");
	    }
	    ideaCloud_html.append(">")
		    .append(inputTag.getTagName())
		    .append("</a></li>");
	}

	ideaCloud_html.add("</ul>")
		.add("</main>")
		.add("</body>")
		.add("</html>");

	// System.out.println("successfully finished.");
    }

    /**
     * Takes this object's {@code HtmlBuilder} attribute and use it to generate an
     * .html file.
     * 
     * @throws IOException
     */
    public void generateOutputFile() throws IOException {
	generateOutputFile(ideaCloud_html);
    }

}
