package de.telekobold.ideacloud.codegenerator;

import java.io.IOException;

/**
 * 
 * @author Michael Merz <mail@telekobold.de>
 */
public class IdeaCloudCssGenerator extends IdeaCloudAbstractGenerator {

    private final CssBuilder ideaCloud_css;

    public IdeaCloudCssGenerator() {
	ideaCloud_css = new CssBuilder();
    }

    public void generateIdeaCloudCssFile() throws IOException {
	ideaCloud_css.comment("This file was generated by IdeaCloudCssGenerator.java")
		.nl()
		.add("* {")
		.add("background-color: black;")
		.add("}")
		.nl();

	generateOutputFile("ideaCloud.css", ideaCloud_css);
    }

}
