package de.telekobold.ideacloud;

import java.io.IOException;

/**
 * 
 * Parts of the generated cloud tag HTML code skeleton are derived from the
 * <a href=
 * "https://dev.to/alvaromontoro/create-a-tag-cloud-with-html-and-css-1e90">cloud
 * tag generation tutorial</a> from Alvaro Montoro.
 * 
 * @author Michael Merz <mail@telekobold.de>
 */
class IdeaCloudHtmlGenerator extends IdeaCloudAbstractGenerator {

    private final HtmlBuilder ideaCloud_html;

    IdeaCloudHtmlGenerator() {
	ideaCloud_html = new HtmlBuilder();
    }

    void generateIdeaCloudHtmlFile(IdeaCloudTriple<String, Integer, String>... inputTags) throws IOException {
	System.out.print("Start HTML file generation... ");

	ideaCloud_html.comment("This file was generated by IdeaCloudHtmlGenerator.java")
		.nl()
		.add("<html>")
		.add("<head>")
		.add("<meta charset=\"utf-8\">")
		.add("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
		.add("</head>")
		.add("<body>")
		.add("<header>")
		.add("<h1>IdeaCloud</h1>")
		.add("</header>")
		.add("<main>")
		.add("<ul class=\"cloud\" role=\"navigation\" aria-label=\"idea tag cloud for planning\">");

	for (IdeaCloudTriple<String, Integer, String> inputTag : inputTags) {
	    ideaCloud_html.add("<li><a href=\"./data/")
		    .append(inputTag.getTagName() + ".html")
		    .append("\" data-weight=\"")
		    .append(Integer.toString(inputTag.getWeight()));
	    if (inputTag.getDeadline() != null) {
		ideaCloud_html.append(" deadline=\"")
			.append(inputTag.getDeadline())
			.append("\"");
	    }
	    ideaCloud_html.append("\">")
		    .append(inputTag.getTagName())
		    .append("</a></li>");
	}

	ideaCloud_html.add("</ul>")
		.add("</main>")
		.add("</body>")
		.add("</html>");

	generateOutputFile("ideaCloud.html", ideaCloud_html);

	System.out.println("successfully finished.");
    }

}
