package de.telekobold.ideacloud;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 * 
 * Parts of the generated cloud tag HTML code skeleton are derived from the
 * <a href=
 * "https://dev.to/alvaromontoro/create-a-tag-cloud-with-html-and-css-1e90">cloud
 * tag generation tutorial</a> from Alvaro Montoro.
 * 
 * @author Michael Merz <mail@telekobold.de>
 */
class IdeaCloudHtmlGenerator {

    private final HtmlBuilder ideaCloud_html;

    IdeaCloudHtmlGenerator() {
	ideaCloud_html = new HtmlBuilder();
    }

    void generateIdeaCloudHtmlFile(IdeaCloudTriple<String, Integer, String>... inputTags) throws IOException {
	System.out.print("Start HTML file generation... ");

	ideaCloud_html.comment("This file was generated by IdeaCloudHtmlGenerator.java")
		.nl()
		.add("<html>")
		.add("<head>")
		.add("<meta charset=\"utf-8\">")
		.add("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
		.add("</head>")
		.add("<body>")
		.add("<header>")
		.add("<h1>")
		.append("IdeaCloud")
		.append("</h1>")
		.add("</header>")
		.add("<main>")
		.add("<ul class=\"cloud\" role=\"navigation\" aria-label=\"idea tag cloud for planning\">");

	for (IdeaCloudTriple inputTag : inputTags) {
	    ideaCloud_html.add("<li><a href=\"")
		    .append("")
		    .append("\" data-weight=\"")
		    .append("")
		    .append("\">")
		    .append("")
		    .append("</a></li>");
	}

	ideaCloud_html.add("</ul>")
		.add("</main>")
		.add("</body>")
		.add("</html>");

	generateOutputFile("ideaCloud.html", ideaCloud_html);

	System.out.println("successfully finished.");
    }

    private static void generateOutputFile(String fileName, HtmlBuilder outputContent) throws IOException {
	// TODO: Gewünschten Speicherort abfragen oder im Home-Verzeichnis in
	// verstecktem Verzeichnis ablegen, oder von Einstellung in GUI abhängig machen.
	File outputFile = new File("/home/telekobold/TestVerzeichnis/IdeaCloudTest/" + fileName);
	outputFile.createNewFile();
	try (BufferedWriter out = new BufferedWriter(new FileWriter(outputFile.getAbsolutePath()));) {
	    out.write(outputContent.toString());
	}

    }
}
