package ideaCloud;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 * 
 * @author Michael Merz <mail@telekobold.de>
 */
class IdeaCloudHtmlGenerator {

    private final HtmlBuilder ideaCloud_html;

    IdeaCloudHtmlGenerator() {
	ideaCloud_html = new HtmlBuilder();
    }

    void generateIdeaCloudHtmlFile() throws IOException {
	// TODO: Der Funktion müssen die zu schreibenden Cloud-Tags als Parameter
	// übergeben werden, am besten als Liste von Tupeln mit (Tag-Name, Gewichtung,
	// deadline), wobei deadline "null" sein kann.
	System.out.print("Start HTML file generation... ");

	ideaCloud_html.comment("This file was generated by IdeaCloudHtmlGenerator.java")
		.nl()
		.add("<html>")
		.add("<head>")
		.add("<meta charset=\"utf-8\">")
		.add("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
		.add("</head>")
		.add("<body>")
		.add("<header>")
		.add("<h1>")
		.append("IdeaCloud")
		.append("</h1>")
		.add("</header>")
		.add("</body>")
		.add("</html>");

	generateOutputFile("ideaCloud.html", ideaCloud_html);

	System.out.println("successfully finished.");
    }

    private static void generateOutputFile(String fileName, HtmlBuilder outputContent) throws IOException {
	File outputFile = new File("/home/telekobold/TestVerzeichnis/IdeaCloudTest/" + fileName);
	outputFile.createNewFile();
	try (BufferedWriter out = new BufferedWriter(new FileWriter(outputFile.getAbsolutePath()));) {
	    out.write(outputContent.toString());
	}

    }
}
