package ideaCloud;

class IdeaCloudHtmlGenerator {

    private final HtmlBuilder ideaCloud_html;

    IdeaCloudHtmlGenerator() {
	ideaCloud_html = new HtmlBuilder();
    }

    void generateIdeaCloudHtmlFile() {
	ideaCloud_html.comment("This file was generated by IdeaCloudHtmlGenerator.java")
		.nl()
		.add("blub");
    }

}
