package ideaCloud;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 * 
 * @author Michael Merz <mail@telekobold.de>
 */
class IdeaCloudHtmlGenerator {

    private final HtmlBuilder ideaCloud_html;

    IdeaCloudHtmlGenerator() {
	ideaCloud_html = new HtmlBuilder();
    }

    void generateIdeaCloudHtmlFile() throws IOException {
	ideaCloud_html.comment("This file was generated by IdeaCloudHtmlGenerator.java")
		.nl()
		.add("<html>")
		.add("<head>")
		.add("<meta charset=\"utf-8\">")
		.add("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
		.add("</head>")
		.add("</html>");

	generateOutputFile("ideaCloud.html", ideaCloud_html);
    }

    private static void generateOutputFile(String fileName, HtmlBuilder outputContent) throws IOException {
	File outputFile = new File("/home/telekobold/TestVerzeichnis/IdeaCloudTest/" + fileName);
	outputFile.createNewFile();
	try (BufferedWriter out = new BufferedWriter(new FileWriter(outputFile.getAbsolutePath()));) {
	    out.write(outputContent.toString());
	}

    }
}
